<a href="https://colab.research.google.com/github/rushimhaisane8830/DS/blob/main/Iris_BaggingClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("Iris.csv")

In [4]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
data["Species"] = LabelEncoder().fit_transform(data["Species"])

In [7]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [9]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [10]:
x_train, x_test, y_train, y_test= train_test_split(x,y , test_size=0.2, random_state=1)

In [11]:
dt = DecisionTreeClassifier()

dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [12]:
y_pred = dt.predict(x_test)

In [13]:
accuracy_score(y_test, y_pred)

0.9666666666666667

In [16]:
from sklearn.ensemble import BaggingClassifier

In [21]:
bag = BaggingClassifier(estimator=dt, n_estimators=100, random_state=1, bootstrap=False, verbose=1, n_jobs=-1)

In [22]:
bag.fit(x_train, y_train)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    4.7s finished

BaggingClassifier(bootstrap=False, estimator=DecisionTreeClassifier(),
                  n_estimators=100, n_jobs=-1, random_state=1, verbose=1)

In [23]:
y_pred1 = bag.predict(x_test)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.1s finished

In [24]:
accuracy_score(y_test, y_pred1)

0.9666666666666667

In [25]:
svc = SVC()

In [26]:
svc.fit(x_train, y_train)

SVC()

In [27]:
y_pred2 = svc.predict(x_test)

In [29]:
accuracy_score(y_test, y_pred2)

0.9333333333333333

In [31]:
lr =  LogisticRegression()

In [32]:
lr.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [33]:
y_pred3 = lr.predict(x_test)

In [34]:
accuracy_score(y_test, y_pred3)

1.0

In [40]:
bag1 = BaggingClassifier(estimator = lr,
                         n_estimators=200,
                         random_state=1,
                         max_samples=0.8,
                         verbose=1,
                         n_jobs=-1)

In [41]:
bag1.fit(x_train, y_train)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    4.5s finished

BaggingClassifier(estimator=LogisticRegression(), max_samples=0.8,
                  n_estimators=200, n_jobs=-1, random_state=1, verbose=1)

In [42]:
y_pred4= bag1.predict(x_test)

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.1s finished

In [43]:
accuracy_score(y_test, y_pred4)

1.0