<a href="https://colab.research.google.com/github/rushimhaisane8830/DS/blob/main/Iris.VotingClassifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
import pandas as pd

In [130]:
data = pd.read_csv("Iris.csv")

In [131]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [132]:
from sklearn.preprocessing import LabelEncoder

In [133]:
data["Species"] = LabelEncoder().fit_transform(data["Species"])

In [134]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [137]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [138]:
from sklearn.model_selection import train_test_split

In [140]:
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=0.2, random_state=1)

In [143]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [144]:
from sklearn.ensemble import VotingClassifier

In [145]:
lr = LogisticRegression()
dt = DecisionTreeClassifier()
svc = SVC(probability=True)

In [146]:
model = VotingClassifier(estimators=[("lr", lr), ("dt", dt), ("svc", svc)], voting="soft")

In [147]:
model.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('dt', DecisionTreeClassifier()),
                             ('svc', SVC(probability=True))],
                 voting='soft')

In [148]:
y_pred = model.predict(x_test)

In [150]:
from sklearn.metrics import accuracy_score

In [151]:
accuracy_score(y_test, y_pred)

0.9666666666666667

In [152]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [153]:
val = [[3,	4.7,	3.2,	1.3,	0.2]]

In [155]:
pred = model.predict(val)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [156]:
pred

array([0])

In [157]:
data.tail(20)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
130  131            7.4           2.8            6.1           1.9        2
131  132            7.9           3.8            6.4           2.0        2
132  133            6.4           2.8            5.6           2.2        2
133  134            6.3           2.8            5.1           1.5        2
134  135            6.1           2.6            5.6           1.4        2
135  136            7.7           3.0            6.1           2.3        2
136  137            6.3           3.4            5.6           2.4        2
137  138            6.4           3.1            5.5           1.8        2
138  139            6.0           3.0            4.8           1.8        2
139  140            6.9           3.1            5.4           2.1        2
140  141            6.7           3.1            5.6           2.4        2
141  142            6.9           3.1            5.1           2.3        2
142  143            5.8           2.7            5.1           1.9        2
143  144            6.8           3.2            5.9           2.3        2
144  145            6.7           3.3            5.7           2.5        2
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

In [158]:
val2 = [[148,	6.5,	3.0,	5.2,	2.0	]]

In [159]:
pred1 = model.predict(val2)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [160]:
pred1

array([2])